"""initial migration

Revision ID: 6ff9ce9efc61
Revises: 
Create Date: 2025-04-07 15:54:13.526781+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ff9ce9efc61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_manufacturer_and_manufacturer_id', 'devices', ['manufacturer', 'manufacturer_id'], unique=False)
    op.create_table('device_measurements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('measurement', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('taken_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_measurements_by_device_id', 'device_measurements', ['device_id'], unique=False)
    op.create_index('ix_ordered_device_measurements_by_device_id_and_measure', 'device_measurements', ['device_id', 'measurement', sa.literal_column('taken_on DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordered_device_measurements_by_device_id_and_measure', table_name='device_measurements')
    op.drop_index('ix_device_measurements_by_device_id', table_name='device_measurements')
    op.drop_table('device_measurements')
    op.drop_index('ix_sensor_manufacturer_and_manufacturer_id', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
