"""create-migration

Revision ID: 4480f1a02a01
Revises: ab0edda4cea7
Create Date: 2025-06-03 18:10:11.633976+00:00

"""
from alembic import op
import sqlalchemy as sa
from uuid import uuid4


# revision identifiers, used by Alembic.
revision = '4480f1a02a01'
down_revision = 'ab0edda4cea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('api_key', sa.String(), nullable=True))
    op.drop_index(op.f('ix_sensor_chip_type_and_chip_id'), table_name='devices')
    op.execute(f"UPDATE devices SET api_key = md5(random()::text)")
    op.alter_column('devices', 'api_key', nullable=False)    
    op.create_index('ix_device_api_key', 'devices', ['api_key'], unique=True)
    op.create_index('ix_device_chip_type_and_chip_id', 'devices', ['chip_type', 'chip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_chip_type_and_chip_id', table_name='devices')
    op.drop_index('ix_device_api_key', table_name='devices')
    op.create_index(op.f('ix_sensor_chip_type_and_chip_id'), 'devices', ['chip_type', 'chip_id'], unique=False)
    op.drop_column('devices', 'api_key')
    # ### end Alembic commands ###
