"""create-migration

Revision ID: e80d4dea2859
Revises: 
Create Date: 2025-05-14 12:06:03.726952+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e80d4dea2859'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('chip_type', sa.String(), nullable=False),
    sa.Column('chip_id', sa.String(), nullable=False),
    sa.Column('chip_model', sa.String(), nullable=True),
    sa.Column('empty_keg_weight', sa.Float(), nullable=True),
    sa.Column('empty_keg_weight_unit', sa.String(), nullable=True),
    sa.Column('start_volume', sa.Float(), nullable=False),
    sa.Column('start_volume_unit', sa.String(), nullable=False),
    sa.Column('display_volume_unit', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), sa.ColumnDefault(1), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_chip_type_and_chip_id', 'devices', ['chip_type', 'chip_id'], unique=False)
    op.create_table('device_measurements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('measurement', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('taken_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_measurements_by_device_id', 'device_measurements', ['device_id'], unique=False)
    op.create_index('ix_ordered_device_measurements_by_device_id_and_measure', 'device_measurements', ['device_id', 'measurement', sa.literal_column('taken_on DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordered_device_measurements_by_device_id_and_measure', table_name='device_measurements')
    op.drop_index('ix_device_measurements_by_device_id', table_name='device_measurements')
    op.drop_table('device_measurements')
    op.drop_index('ix_sensor_chip_type_and_chip_id', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
