"""create-migration

Revision ID: 584934a825cf
Revises: 4480f1a02a01
Create Date: 2025-06-11 21:01:51.499795+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584934a825cf'
down_revision = '4480f1a02a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_accounts_api_key', 'service_accounts', ['api_key'], unique=True)
    op.create_index('ix_service_accounts_name', 'service_accounts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_accounts_name', table_name='service_accounts')
    op.drop_index('ix_service_accounts_api_key', table_name='service_accounts')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
