"""Add Users Table

Revision ID: ab0edda4cea7
Revises: e80d4dea2859
Create Date: 2025-06-02 10:48:10.963581+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0edda4cea7'
down_revision = 'e80d4dea2859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('google_oidc_id', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_api_key', 'users', ['api_key'], unique=True)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.create_index('ix_user_google_oidc_id', 'users', ['google_oidc_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_google_oidc_id', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_api_key', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
