version: '3.8'
services:
  kvm_nginx: 
    image : nginx:latest 
    ports : 
        - 8001:8001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - keg-volume-monitor-net
    depends_on:
      - kvm_web
  kvm_web:
    image: keg-volume-monitor:dev
    expose:
      - 5000
    ports:
      - 5000
    env_file:
      - ./docker-local.env
      - ".env"
    depends_on:
      kvm_postgres:
        condition: service_healthy
      kvm_db-data-seed:
        condition: service_completed_successfully
    networks:
      - keg-volume-monitor-net
    volumes:
      - ./my-config.json:/keg-volume-monitor/config/config.json
    stdin_open: true
    tty: true
  kvm_postgres:
    image: postgres:17-alpine
    expose:
      - 5433
    ports:
      - 5433:5433
    networks:
      - keg-volume-monitor-net
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./docker-local.env
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -p $$POSTGRES_PORT"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    command: -p 5433
  kvm_db-data-seed:
    image: keg-volume-monitor-db-seed:dev
    depends_on:
      kvm_postgres:
        condition: service_healthy
    env_file:
      - ./docker-local.env
      - ".env"
    volumes:
      - ./my-config.json:/keg-volume-monitor/config/config.json
    networks:
      - keg-volume-monitor-net
networks:
  keg-volume-monitor-net:
      